In [1]:
import pandas as pd

data = pd.read_csv(
    r"C:\Users\trupt\Downloads\archive (3)\SMSSpamCollection",
    sep="\t",
    header=None,
    names=["label", "message"]
)

data.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [2]:
data.shape

(5572, 2)

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   label    5572 non-null   object
 1   message  5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [4]:
data["label"].value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

In [5]:
 data.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
data.tail()

     label                                            message
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

In [7]:
data.shape

(5572, 2)

In [8]:
data.columns

Index(['label', 'message'], dtype='object')

In [9]:
data.dtypes

label      object
message    object
dtype: object

In [10]:
data.isnull().sum()

label      0
message    0
dtype: int64

In [11]:
data["label"].value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

In [12]:
data["label"].value_counts(normalize=True) * 100

label
ham     86.593683
spam    13.406317
Name: proportion, dtype: float64

In [13]:
data["label"] = data["label"].map({"ham": 0, "spam": 1})

In [14]:
data.head()

   label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [15]:
data["message"] = data["message"].str.lower()

In [16]:
data.head()

   label                                            message
0      0  go until jurong point, crazy.. available only ...
1      0                      ok lar... joking wif u oni...
2      1  free entry in 2 a wkly comp to win fa cup fina...
3      0  u dun say so early hor... u c already then say...
4      0  nah i don't think he goes to usf, he lives aro...

In [17]:
import string

data["message"] = data["message"].str.translate(
    str.maketrans("", "", string.punctuation)
)

In [18]:
data.head()

   label                                            message
0      0  go until jurong point crazy available only in ...
1      0                            ok lar joking wif u oni
2      1  free entry in 2 a wkly comp to win fa cup fina...
3      0        u dun say so early hor u c already then say
4      0  nah i dont think he goes to usf he lives aroun...

In [19]:
data["message"] = data["message"].str.strip()

In [20]:
data["tokens"] = data["message"].str.split()

In [21]:
data[["message", "tokens"]].head()

,message,tokens
0,go until jurong point crazy available only in ...,"[go, until, jurong, point, crazy, available, o..."
1,ok lar joking wif u oni,"[ok, lar, joking, wif, u, oni]"
2,free entry in 2 a wkly comp to win fa cup fina...,"[free, entry, in, 2, a, wkly, comp, to, win, f..."
3,u dun say so early hor u c already then say,"[u, dun, say, so, early, hor, u, c, already, t..."
4,nah i dont think he goes to usf he lives aroun...,"[nah, i, dont, think, he, goes, to, usf, he, l..."

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words="english")

X = tfidf.fit_transform(data["message"])

y = data["label"]

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [25]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train, y_train)

MultinomialNB()

In [28]:
y_pred = model.predict(X_test)

In [27]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.9659192825112107

In [29]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[966,   0],
       [ 38, 111]], dtype=int64)

In [30]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       966
           1       1.00      0.74      0.85       149

    accuracy                           0.97      1115
   macro avg       0.98      0.87      0.92      1115
weighted avg       0.97      0.97      0.96      1115

In [31]:
sample = ["Congratulations! You have won a free iPhone. Click here now."]

sample = tfidf.transform(sample)

prediction = model.predict(sample)

if prediction[0] == 1:
    print("Spam")
else:
    print("Ham")

Spam

In [32]:
sample = ["Hi, where are you? Let's meet at 5 PM."]

sample = tfidf.transform(sample)

prediction = model.predict(sample)

if prediction[0] == 1:
    print("Spam")
else:
    print("Ham")

Ham

In [34]:
import joblib

joblib.dump(model, "spam_classifier.pkl")
joblib.dump(tfidf, "tfidf_vectorizer.pkl")

['tfidf_vectorizer.pkl']

 # The SMS Spam Detection model was built using the SMS Spam Collection dataset. The text messages were preprocessed by converting them to lowercase, removing punctuation, and transforming them into TF-IDF features. A Multinomial Naive Bayes classifier was trained and evaluated. The model successfully classified SMS messages as spam or ham with high accuracy."